# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.location import Location  # noqa: F401,E501
from swagger_server import util


class SAP(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, c_pid: str=None, vnf_link: str=None, location: Location=None):  # noqa: E501
        """SAP - a model defined in Swagger

        :param c_pid: The c_pid of this SAP.  # noqa: E501
        :type c_pid: str
        :param vnf_link: The vnf_link of this SAP.  # noqa: E501
        :type vnf_link: str
        :param location: The location of this SAP.  # noqa: E501
        :type location: Location
        """
        self.swagger_types = {
            'c_pid': str,
            'vnf_link': str,
            'location': Location
        }

        self.attribute_map = {
            'c_pid': 'CPid',
            'vnf_link': 'VNFLink',
            'location': 'location'
        }
        self._c_pid = c_pid
        self._vnf_link = vnf_link
        self._location = location

    @classmethod
    def from_dict(cls, dikt) -> 'SAP':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The SAP of this SAP.  # noqa: E501
        :rtype: SAP
        """
        return util.deserialize_model(dikt, cls)

    @property
    def c_pid(self) -> str:
        """Gets the c_pid of this SAP.

        Id of the associated CP  # noqa: E501

        :return: The c_pid of this SAP.
        :rtype: str
        """
        return self._c_pid

    @c_pid.setter
    def c_pid(self, c_pid: str):
        """Sets the c_pid of this SAP.

        Id of the associated CP  # noqa: E501

        :param c_pid: The c_pid of this SAP.
        :type c_pid: str
        """

        self._c_pid = c_pid

    @property
    def vnf_link(self) -> str:
        """Gets the vnf_link of this SAP.

        ID of the associated VNFLink  # noqa: E501

        :return: The vnf_link of this SAP.
        :rtype: str
        """
        return self._vnf_link

    @vnf_link.setter
    def vnf_link(self, vnf_link: str):
        """Sets the vnf_link of this SAP.

        ID of the associated VNFLink  # noqa: E501

        :param vnf_link: The vnf_link of this SAP.
        :type vnf_link: str
        """

        self._vnf_link = vnf_link

    @property
    def location(self) -> Location:
        """Gets the location of this SAP.


        :return: The location of this SAP.
        :rtype: Location
        """
        return self._location

    @location.setter
    def location(self, location: Location):
        """Sets the location of this SAP.


        :param location: The location of this SAP.
        :type location: Location
        """

        self._location = location
