# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.cp import CP  # noqa: F401,E501
from swagger_server.models.vnf_requirements import VNFRequirements  # noqa: F401,E501
from swagger_server import util


class VNF(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, vn_fid: str=None, cp: List[CP]=None, instances: float=None, requirements: VNFRequirements=None, failure_rate: float=None, processing_latency: float=None):  # noqa: E501
        """VNF - a model defined in Swagger

        :param vn_fid: The vn_fid of this VNF.  # noqa: E501
        :type vn_fid: str
        :param cp: The cp of this VNF.  # noqa: E501
        :type cp: List[CP]
        :param instances: The instances of this VNF.  # noqa: E501
        :type instances: float
        :param requirements: The requirements of this VNF.  # noqa: E501
        :type requirements: VNFRequirements
        :param failure_rate: The failure_rate of this VNF.  # noqa: E501
        :type failure_rate: float
        :param processing_latency: The processing_latency of this VNF.  # noqa: E501
        :type processing_latency: float
        """
        self.swagger_types = {
            'vn_fid': str,
            'cp': List[CP],
            'instances': float,
            'requirements': VNFRequirements,
            'failure_rate': float,
            'processing_latency': float
        }

        self.attribute_map = {
            'vn_fid': 'VNFid',
            'cp': 'CP',
            'instances': 'instances',
            'requirements': 'requirements',
            'failure_rate': 'failure_rate',
            'processing_latency': 'processing_latency'
        }
        self._vn_fid = vn_fid
        self._cp = cp
        self._instances = instances
        self._requirements = requirements
        self._failure_rate = failure_rate
        self._processing_latency = processing_latency

    @classmethod
    def from_dict(cls, dikt) -> 'VNF':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VNF of this VNF.  # noqa: E501
        :rtype: VNF
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vn_fid(self) -> str:
        """Gets the vn_fid of this VNF.

        VNF identifier  # noqa: E501

        :return: The vn_fid of this VNF.
        :rtype: str
        """
        return self._vn_fid

    @vn_fid.setter
    def vn_fid(self, vn_fid: str):
        """Sets the vn_fid of this VNF.

        VNF identifier  # noqa: E501

        :param vn_fid: The vn_fid of this VNF.
        :type vn_fid: str
        """
        if vn_fid is None:
            raise ValueError("Invalid value for `vn_fid`, must not be `None`")  # noqa: E501

        self._vn_fid = vn_fid

    @property
    def cp(self) -> List[CP]:
        """Gets the cp of this VNF.


        :return: The cp of this VNF.
        :rtype: List[CP]
        """
        return self._cp

    @cp.setter
    def cp(self, cp: List[CP]):
        """Sets the cp of this VNF.


        :param cp: The cp of this VNF.
        :type cp: List[CP]
        """

        self._cp = cp

    @property
    def instances(self) -> float:
        """Gets the instances of this VNF.

        Number of instances of this VNF to deploy  # noqa: E501

        :return: The instances of this VNF.
        :rtype: float
        """
        return self._instances

    @instances.setter
    def instances(self, instances: float):
        """Sets the instances of this VNF.

        Number of instances of this VNF to deploy  # noqa: E501

        :param instances: The instances of this VNF.
        :type instances: float
        """

        self._instances = instances

    @property
    def requirements(self) -> VNFRequirements:
        """Gets the requirements of this VNF.


        :return: The requirements of this VNF.
        :rtype: VNFRequirements
        """
        return self._requirements

    @requirements.setter
    def requirements(self, requirements: VNFRequirements):
        """Sets the requirements of this VNF.


        :param requirements: The requirements of this VNF.
        :type requirements: VNFRequirements
        """
        if requirements is None:
            raise ValueError("Invalid value for `requirements`, must not be `None`")  # noqa: E501

        self._requirements = requirements

    @property
    def failure_rate(self) -> float:
        """Gets the failure_rate of this VNF.

        Probability that a VNF instance of this type fails.  # noqa: E501

        :return: The failure_rate of this VNF.
        :rtype: float
        """
        return self._failure_rate

    @failure_rate.setter
    def failure_rate(self, failure_rate: float):
        """Sets the failure_rate of this VNF.

        Probability that a VNF instance of this type fails.  # noqa: E501

        :param failure_rate: The failure_rate of this VNF.
        :type failure_rate: float
        """

        self._failure_rate = failure_rate

    @property
    def processing_latency(self) -> float:
        """Gets the processing_latency of this VNF.

        Latency for a VNF instance with the specific characteristics to process a service request.  # noqa: E501

        :return: The processing_latency of this VNF.
        :rtype: float
        """
        return self._processing_latency

    @processing_latency.setter
    def processing_latency(self, processing_latency: float):
        """Sets the processing_latency of this VNF.

        Latency for a VNF instance with the specific characteristics to process a service request.  # noqa: E501

        :param processing_latency: The processing_latency of this VNF.
        :type processing_latency: float
        """

        self._processing_latency = processing_latency
